### ISSUE TITLE
vapi APIs are not working locally

### ISSUE THREAD

**Issue by vedantchauhan** [roottusk/vapi#10]
Hi, 

I am new to API vulnerability checking using vapi. I am using docker-compose to run the vapi application in my local as shown below:
![image](https://user-images.githubusercontent.com/32234165/124702964-c026e500-df34-11eb-9d42-a933b48503cd.png)

The first issue is that I cannot access the documentation of vapi using http://loclahost:8082/vapi even though docker is running.
The second issue, since vapi is running locally, I am using postman to access the APIs and always receive the following error:
![image](https://user-images.githubusercontent.com/32234165/124703250-4e02d000-df35-11eb-9ff2-ae467e934ecf.png)

Would you please provide any help on this? Thanks.

**Comment by roottusk** [comment]
Hi Vedant ,

Could you check the docker interfaces running using ipco fig , Mostly the issue might be that the service might not be running on localhost but another IP/interface , Can you also confirm through netstat if the ports are open and listening on 127.0.0.1:8082 .

If this does not solve the issue ,let me know if we can connect

**Comment by vedantchauhan** [comment]
Thanks for your help, it worked.
