### ISSUE TITLE
error create user API1

### ISSUE THREAD

**Issue by oryonfarias** [roottusk/vapi#18]
in the old version I managed to go to API5 and it started to give an error.
After the update, When creating the user for testing, i get this feedback in postman;

{
    "errorInfo": [
        "23000",
        1062,
        "Duplicate entry '' for key 'a_p_i1_users.username'"
    ]
}

**Comment by roottusk** [comment]
Can you try registering with a different username?

**Comment by oryonfarias** [comment]
yes, i created a new user!

it worked now

but I had to edit it in the postman to send the data in the body as "raw"! if i send "x-www-form-urlencoded" returns error. this for all API labs, I've tested up to API7! obg for the return and for the project!

**Comment by oryonfarias** [comment]
thanks for the feedback and the project!

**Comment by roottusk** [comment]
Yes the recent master branch is a laravel project which we are still doing hence the Request Body is raw(application/json) , for previous versions you can check releases. Also the Postman folder contains the latest collection that can be used. Hope you're issue is solved. :)
