### ISSUE TITLE
Collections in Public Workspace for Training Purposes

### ISSUE THREAD

**Issue by kinlane** [roottusk/vapi#2]
Hey now! Great resource! I'd love to see your collection + environment setup in a public workspace so that I can use as part of trainings and demos. [I went ahead and setup one to show you what is possible](https://www.postman.com/api-evangelist/workspace/vulnerable-adversely-programmed-interface-vapi/overview) -- would prefer if it was setup under your own account so you could evolve the collections. If / when you setup, let me know and I'll remove mine and I'll just fork your collections.

**Comment by roottusk** [comment]
Hi @kinlane ,

Thank you for your suggestion ,I had actually used this project in a private training and that time it was there in a private workspace.I have went ahead and created a separate public workspace for this https://www.postman.com/roottusk/workspace/vapi/
Let me know if this works :)
