### ISSUE TITLE
VAPI3

### ISSUE THREAD

**Issue by oryonfarias** [roottusk/vapi#23]
please how to configure apk "the Company App"?
configure http://localhost/vapi/
then I tried to register a user on the App but nothing happens!

I noticed that there was an update to the App. In the previous version I logged in with
testuser:test123

**Comment by oryonfarias** [comment]
> For the New Version you can mention the base url as
> 
> yourip/vapi in the APK
> 
> What error are you getting while registering user in the App? It may already been registered. So try using the credentials for login There is a API Call given in the Postman Collection as well "Create User" for API3, you can use it to create the User and use same credentials for the APK

**Comment by roottusk** [comment]
The Mobile and the vAPI have to be on the same network or the vAPI should be accessible over the Internet so connection issues aren't there. Was the issue resolved?

**Comment by roottusk** [comment]
Sorry I am not on Telegram, Can you email it to me on root.tusk@gmail.com ?

**Comment by roottusk** [comment]
Hi ,

We checked this issue and We are able to reproduce it. Will work on fixing it
