### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by AndyG-0** [roottusk/vapi#26]
This would be an enhancement. Has any thoughts been given to creating a helm chart for deploying to Kubernetes?

**Comment by roottusk** [comment]
I have very little to no idea about Kubernetes and Helm charts , if anyone else takes this . I would be happy to look at the PR. Otherwise it will take some time for me to look at this

**Comment by AndyG-0** [comment]
I have much of this already working. I can get a pr going to add it in. The helm chart will also be pulling in the images from Docker Hub. It doesn't look like there is currently a process to have them published when the code changes. This may be something else to look into. I can maybe help with it as well. I'm guessing maybe this would be a different GitHub Issue.

**Comment by roottusk** [comment]
Sure
