### ISSUE TITLE
Updating php/apache base image

### ISSUE THREAD

**Issue by AndyG-0** [roottusk/vapi#27]
The php/apache base image in the dockerfile has some known vulnerabilities in it. Upgrading to the latest version(php:8.1.2-apache) removes the vulnerabilities but breaks the code.  I have not had time to dig into the errors yet to see what it would take to get it to work with the latest php docker image.

**Comment by roottusk** [comment]
I think version 8.x and 7.x would be having major syntax changes , I tried running with php:7.4.26-apache image and it seems to run well ( yet to get into any error) , migrating it to 8.x though would require some work .

**Comment by AndyG-0** [comment]
Not sure why I didn't try a higher minor version of the major version first but I can say that php:7.4.27-apache removes any critical vulnerabilities. I haven't had a chance to fully test yet but I'm guessing it's probably ok. 7.4.26 had less vulnerabilities but still had some.

**Comment by AndyG-0** [comment]
#28 would also update this to 7.4.27.
