### ISSUE TITLE
Can't automatic install 

### ISSUE THREAD

**Issue by pwndumb** [roottusk/vapi#29]
I try automatic install with docker-compose up -d but it fails in dns resolution
![image](https://user-images.githubusercontent.com/6491534/163684281-fba49e09-e085-4ce5-b7cd-dd27066c49aa.png)

![image](https://user-images.githubusercontent.com/6491534/163684302-cf972fbe-72c2-4e0c-8fd4-fc4f15268c14.png)

**Comment by roottusk** [comment]
I think it is something to do with you source.list file maybe, if I clone the project fresh and run it works for me. Try cloning from the  `master` branch and running instead of the release files if that work.
