### ISSUE TITLE
api1 authHeader

### ISSUE THREAD

**Issue by KenV1040** [roottusk/vapi#32]
Hello,
Apologies if this is the wrong place to ask this. 
Working on api1 problem currently and when trying to get user it's asking for an authHeader. However, when I create user, it doesn't return one. And there's no login endpoint for api1 either. Is there something I'm missing? Is this part of the task?

**Comment by roottusk** [comment]
Hey,

Try to send it from the postman environment directly. There is a postman
script which generates auth header by doing
base64_encode(username:password). Let me know if you face any issues using
it through postman

**Comment by KenV1040** [comment]
Is that script supposed to run when I run createUser endpoint? Because I imported the OpenAPI json file into postman and I was testing it form postman. I went and create a new user, got the success response, then tried to run the get user and replaced the userID with the userID I got from the createUser endpoint, and I get an empty response

**Comment by roottusk** [comment]
Hey,
May I know if you downloaded the OpenAPI Json from the localhost/vapi URL? If yes then thats just a converted documentation through redocly. I suggest you use the Postman Collection and Environment from postman folder below.

https://github.com/roottusk/vapi/tree/master/postman

let me know if this works

**Comment by KenV1040** [comment]
Hello,

Yeah you were right. I was using the json from the localhost. That was the issue. I downloaded the one from the github and it works perfectly now. Thanks for your help!
