### ISSUE TITLE
Compatibility with Docker Playground ?

### ISSUE THREAD

**Issue by HeIp** [roottusk/vapi#34]
I am trying to run this on https://labs.play-with-docker.com
My process :
1)clone
2)cd in vapi and run docker command

But /vapi page does not load ?
<img width="754" alt="Screen Shot 2022-06-18 at 7 40 54 PM" src="https://user-images.githubusercontent.com/31706214/174460271-37b94262-553d-4eda-9171-f07f9b756fe1.png">

**Comment by HeIp** [comment]
using mogenius, also had issues

**Comment by roottusk** [comment]
@AndyG-0 I think people are having issues with the new docker-compose.yml

**Comment by roottusk** [comment]
I will check this out again on my end and let you know

**Comment by AndyG-0** [comment]
@roottusk LMK if you find something. I've tested several times and am unable to re-create any issues with the docker-compose. @HeIp have you tried running with docker locally? When you say it does not load are you getting an error? Are there any errors in the log?

**Comment by HeIp** [comment]
I dont see any errors in the log, have you tried setting it up in https://labs.play-with-docker.com/ ? As I only ran the docker compose command
