### ISSUE TITLE
mysql env on the laravel pod are not set

### ISSUE THREAD

**Issue by alexnimo** [roottusk/vapi#41]
After deploying on GKE I constantly received error messages related to the DB when sending requests.
After verifying that it was not connectivity or a DB issue I suspected it is a configuration issue.
I've constantly received an error message:

**Access denied for user 'forge'@'<pod IP address>' (using password: NO)**

I tried to look for the .env file which is supposed to set the correct value into that database.php file but haven't found one.
stumbled upon this StackOverflow thread:
https://stackoverflow.com/questions/42148086/laravel-5-error-sqlstatehy000-1045-access-denied-for-user-forgelocalhost

After changing manually the configuration in the database.php file to the correct values everything started working as it should...

**Comment by roottusk** [comment]
This has been fixed I believe
