### ISSUE TITLE
Temporary failure resolving 'deb.debian.org'

### ISSUE THREAD

**Issue by lianglc** [roottusk/vapi#45]
Just clone the latest from github, with next command `sudo docker-compose up -d`, I was lead to following errors. 
<img width="1280" alt="Screenshot 2023-03-22 at 11 41 03 AM" src="https://user-images.githubusercontent.com/13939729/226796824-0dd18407-493b-4897-8b4c-945fbf31d0ca.png">

**Comment by roottusk** [comment]
I believe this a DNS problem . Can you check and update your DNS server so that you're able to resolve deb.debian.org?

Thanks

**Comment by lianglc** [comment]
I am able to open an browser with http://deb.debian.org even though ping does not provide response. 
It seem current file is under http://ftp.debian.org/debian/dists/bullseye/InRelease, is this making any difference? 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/13939729/226804031-1de57d40-2cf1-4c0a-abe1-0fc2c2b0bc17.png">

**Comment by lianglc** [comment]
NM, http://deb.debian.org/debian/dists/bullseye/InRelease seem reachable to the file content from browser too.

**Comment by dayveedo1** [comment]
I also faced similar problem, any solutions to this?

**Comment by AhmetSerkann** [comment]
Hi, i also faced same problem. Any solutions to this?

**Comment by roottusk** [comment]
https://stackoverflow.com/questions/61567404/docker-temporary-failure-resolving-deb-debian-org

**Comment by AhmetSerkann** [comment]
@roottusk Thank you, its working. 👉🏻👈🏻
